import React from 'react';
import type { Metadata } from 'next';
import { CommonTitle } from '@/components/ui';

export const metadata: Metadata = {
  title: 'О компании Форест Тревел',
  // description: 'Generated by create next app',
};

export default function AboutCompany() {
  return (
    <div>
      <CommonTitle titneName="О компании Форест Тревел" />
    </div>
  );
}
