import React from 'react';
import type { Metadata } from 'next';
import { CommonTitle } from '@/components/ui';

import { BlockCard, Container } from '@/components/shared';

export const metadata: Metadata = {
  title: 'Туры и направления - агенство Форест Тревел',
  // description: 'Generated by create next app',
};

const list = [
  { id: 1, name: 'Бесплатные туры', altImg: 'img1.jpg' },
  { id: 2, name: 'Экстремальный отдых', altImg: 'img1.jpg' },
  { id: 3, name: 'Невероятные приключения', altImg: 'img1.jpg' },
  { id: 4, name: 'Трекинг походы', altImg: 'img1.jpg' },
  { id: 5, name: ' Экзотические джунгли', altImg: 'img1.jpg' },
  { id: 6, name: 'Курорт', altImg: 'img1.jpg' },
];

export default function ToursDestinations() {
  return (
    <div className="">
      <CommonTitle titneName="Туры и направления" />
      <Container>
        {list.map((item) => (
          <BlockCard key={item.id} nameBlock={item.name} />
        ))}
      </Container>
    </div>
  );
}
