import React from 'react';
import type { Metadata } from 'next';
import { CommonTitle } from '@/components/ui';

export const metadata: Metadata = {
  title: 'Туры и направления - агенство Форест Тревел',
  // description: 'Generated by create next app',
};

export default function ToursDestinations() {
  return (
    <div>
      <CommonTitle titneName="Туры и направления" />
    </div>
  );
}
