import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Туристическое агенство Форест Тревел',
  // description: 'Generated by create next app',
};

export default function Home() {
  return <div></div>;
}
