import React from 'react';
import type { Metadata } from 'next';
import { CommonTitle } from '@/components/ui';

export const metadata: Metadata = {
  title: 'Галерея - агенство Форест Тревел',
  // description: 'Generated by create next app',
};

export default function Gallery() {
  return (
    <div>
      <CommonTitle titneName="Галерея" />
    </div>
  );
}
