import React from 'react';
import type { Metadata } from 'next';
import { CommonTitle } from '@/components/ui';

export const metadata: Metadata = {
  title: 'Контакты - агенство Форест Тревел',
  // description: 'Generated by create next app',
};

export default function Contacts() {
  return (
    <div>
      <CommonTitle titneName="Контактная информация" />
    </div>
  );
}
